### ISSUE TITLE
Version list of installed packages

### ISSUE THREAD

**Issue by ruoyxue** [proger/hippogriff#2]
I met errors when installing flash-attn and accelerated_scan (their needed torch versions are different), could you please provide the version list of the installed python packages? Thanks!

**Comment by proger** [comment]
Any set that matches constrains specified in `setup.py` will do for now.

Here's what I have:

```
proger;; pip list |egrep 'torch |accelerated-scan|flash-attn'
accelerated-scan          0.1.1            /home/proger/accelerated-scan
flash-attn                2.4.2
torch                     2.1.2
```
